title: Yash Patel # your name (or website title) here
logo: "/images/DALL·E 2023-03-30 22.45.10 - logo design _YP_.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi I am Yash Patel. A recent Electrical and Computer Engineering graduate with a specialisation in Artificial Intelligence and Machine Learning seeking entry-level opportunities as a data scientist or machine learning engineer. Proficient in programming languages such as Python, C++, Java, Javascript, R, with experience in data wrangling, statistical analysis, and machine learning algorithms. Skilled in data visualization and interpretation, with a strong ability to communicate insights effectively. Looking to apply my skills and knowledge in a challenging and dynamic work environment.
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
